baseURL = "http://www.waptug.org"
publishdir = "/var/www/html/"
languageCode = "en-us"
title = "WapTug.Org"
theme = "ananke"


MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6096 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/groups/WARPJams"
  twitter = "https://twitter.com/waptug"
  instagram = ""
  youtube = "https://youtube.com/WapTugDotOrg"
  github = "https://github.com/waptug"
  gitlab = "https://gitlab.com/waptug"
  linkedin = "https://linkedin.com/in/geekzonebooks"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 20
  disqusShortname = "waptug-org"
  HUGO_ENV="production"
  show_reading_time= true
  site_logo = "images/logo-small.png"
  commentoEnable = true
  
    

[outputs]
  home = ["HTML", "RSS", "JSON"]